#!/usr/bin/env python3
"""Validate the source catalog and render its Markdown views (standard library only)."""

import argparse
from collections import Counter
from datetime import date
from html import escape
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit

from figures import render_credits, render_interface, validate_figures
from daily import render_daily, validate_daily

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "models.json"
FIGURES = ROOT / "data" / "figures.json"
DAILY = ROOT / "data" / "tts-arxiv-daily.json"
CATEGORIES = {
    "concatenative": ("Rule-based and concatenative synthesis", "concatenative.md", "Concatenative"),
    "autoregressive": ("Autoregressive acoustic models", "autoregressive.md", "Autoregressive"),
    "parallel": ("Parallel acoustic models", "parallel.md", "Parallel"),
    "flow-vae": ("Normalizing flows and variational models", "flow-vae.md", "Flow / VAE"),
    "diffusion": ("Diffusion and flow matching", "diffusion.md", "Diffusion / flow"),
    "token-lm": ("Speech-token language models", "token-lm.md", "Token LM"),
    "continuous-lm": ("Continuous speech language models", "continuous-lm.md", "Continuous LM"),
    "compact": ("Compact and on-device TTS", "compact.md", "Compact"),
    "api": ("Commercial TTS interfaces", "api.md", "API"),
}
MODALITIES = {"T", "A", "S", "I", "V"}
INTERACTIONS = {"generation", "streaming"}
SOURCE_KINDS = {"paper", "repository", "model-card", "documentation", "announcement", "project"}
REVIEWS = {"abstract", "paper", "readme", "model-card", "documentation", "announcement", "project"}
LEGEND = "**Inputs and outputs:** T = text, S = speech, A = other audio, I = image, V = video. Speech input usually means an optional voice or prosody reference. For acoustic models, output includes the accompanying waveform synthesizer. See the [methodology](../docs/methodology.md#modalities-and-interaction)."
GENERATED = "<!-- Generated by scripts/catalog.py from data/models.json and data/figures.json. Edit the JSON, then regenerate. -->"


def cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def sorted_models(models):
    return sorted(models, key=lambda m: (m["name"].casefold(), m["id"]))


def link(model, prefix=""):
    return f'{prefix}models/{CATEGORIES[model["category"]][1]}#{model["id"]}'


def io(model):
    return f'{", ".join(model["inputs"])} → {", ".join(model["outputs"])}'


def sources(model):
    labels = {"paper": "Paper", "repository": "GitHub", "model-card": "Model card", "documentation": "Docs", "announcement": "Announcement", "project": "Project"}
    totals = Counter(s["kind"] for s in model["sources"])
    seen = Counter()
    links = []
    for source in model["sources"]:
        kind = source["kind"]
        seen[kind] += 1
        label = labels[kind] + (f" {seen[kind]}" if totals[kind] > 1 else "")
        links.append(f'[{label}]({source["url"]})')
    if model.get("github_status") == "not-found":
        links.append("GitHub: no author-linked repository found")
    return " · ".join(links)


def iso_date(value, context):
    if not isinstance(value, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        raise ValueError(f"{context}: expected YYYY-MM-DD")
    return date.fromisoformat(value)


def validate(catalog):
    if catalog.get("schema_version") != 1:
        raise ValueError("Unsupported schema_version")
    cutoff = iso_date(catalog["as_of"], "as_of")
    models = catalog["models"]
    if not isinstance(models, list) or not models:
        raise ValueError("models must be a nonempty list")
    ids, names = set(), set()
    required = {"id", "name", "category", "inputs", "outputs", "interaction", "architecture", "notes", "variants", "source_date", "source_date_kind", "sources"}
    optional = {"description", "github_status"}
    for m in models:
        missing, unexpected = required - set(m), set(m) - required - optional
        if missing or unexpected:
            raise ValueError(f'{m.get("id", "entry")}: missing fields {missing}; unexpected fields {unexpected}')
        mid = m["id"]
        if not isinstance(mid, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", mid) or mid in ids:
            raise ValueError(f"Invalid or duplicate id: {mid}")
        ids.add(mid)
        for field in ("name", "architecture", "notes"):
            if not isinstance(m[field], str) or not m[field].strip():
                raise ValueError(f"{mid}: {field} must contain text")
        if "description" in m and (not isinstance(m["description"], str) or not m["description"].strip()):
            raise ValueError(f"{mid}: description must contain text when provided")
        if "github_status" in m:
            if m["github_status"] not in {"author-linked", "not-found"}:
                raise ValueError(f"{mid}: invalid GitHub review status")
            has_github = any(s["kind"] == "repository" and urlsplit(s["url"]).hostname == "github.com" for s in m["sources"])
            if has_github != (m["github_status"] == "author-linked"):
                raise ValueError(f"{mid}: GitHub status disagrees with repository sources")
        if m["name"].casefold() in names:
            raise ValueError(f'{mid}: duplicate name; disambiguate separate models')
        names.add(m["name"].casefold())
        if m["category"] not in CATEGORIES or m["interaction"] not in INTERACTIONS:
            raise ValueError(f"{mid}: unknown category or interaction")
        for field in ("inputs", "outputs"):
            values = m[field]
            if not isinstance(values, list) or not values or not all(isinstance(x, str) for x in values) or len(values) != len(set(values)) or not set(values) <= MODALITIES:
                raise ValueError(f"{mid}: invalid {field}")
        variants = m["variants"]
        if not isinstance(variants, list) or not all(isinstance(v, str) and v.strip() for v in variants) or len(variants) != len(set(variants)):
            raise ValueError(f"{mid}: invalid variants")
        if m["source_date"] is None:
            if m["source_date_kind"] is not None:
                raise ValueError(f"{mid}: date kind requires a date")
        elif iso_date(m["source_date"], mid) > cutoff or m["source_date_kind"] not in {"paper", "announcement"}:
            raise ValueError(f"{mid}: invalid or future source date")
        if not isinstance(m["sources"], list) or not m["sources"]:
            raise ValueError(f"{mid}: at least one primary source required")
        urls = set()
        for source in m["sources"]:
            if set(source) != {"kind", "title", "url", "reviewed_on", "review_level"}:
                raise ValueError(f"{mid}: invalid source fields")
            url = urlsplit(source["url"])
            if url.scheme != "https" or not url.netloc or url.username or url.password or source["url"] in urls or re.search(r"\s", source["url"]):
                raise ValueError(f"{mid}: invalid/duplicate HTTPS source")
            urls.add(source["url"])
            if source["kind"] not in SOURCE_KINDS or source["review_level"] not in REVIEWS or not source["title"].strip():
                raise ValueError(f"{mid}: invalid source metadata")
            if iso_date(source["reviewed_on"], mid) > cutoff:
                raise ValueError(f"{mid}: source reviewed after cutoff")
        if m["source_date_kind"] == "paper" and not any(s["kind"] == "paper" for s in m["sources"]):
            raise ValueError(f"{mid}: paper date without a paper source")
        if "T" not in m["inputs"] or "S" not in m["outputs"]:
            raise ValueError(f"{mid}: TTS entries require text input and speech output")


def render_category(key, models, cutoff, figures):
    title = CATEGORIES[key][0]
    lines = [f"# {title}", "", GENERATED, "", "[← All models](../README.md#models)", "", f"**{len(models)} {'model' if len(models) == 1 else 'models'} · Reviewed {cutoff}**", "", "Primary-source figures and labeled input/output diagrams. [Figure credits](../assets/architectures/CREDITS.md).", "", '<details>', '<summary>Model index and modality key</summary>', "", LEGEND, "", "Dates refer to papers or announcements, not necessarily model releases.", "", "| Model | Source date | Input → output | Interaction |", "| --- | --- | --- | --- |"]
    for m in models:
        lines.append(f'| [{cell(m["name"])}](#{m["id"]}) | {m["source_date"] or "—"} | {io(m)} | {m["interaction"]} |')
    lines += ["", "</details>", "", "## Architectures", ""]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Input/output diagram" if figure["kind"] == "io-diagram" else figure["locator"]
        lines += [
            f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "",
            m["architecture"].rstrip(".") + ".", "",
        ]
        if m.get("description"):
            lines += [m["description"], ""]
        lines += [
            sources(m), "",
            f'![{cell(m["name"])} — {visual_type}](../{figure["path"]})', "",
            f'*{visual_type} · [Source]({figure["source_url"]})*', "",
            "<details>", "<summary>Details</summary>", "",
            f'**Input → output:** {io(m)} · **Interaction:** {m["interaction"]}', "", m["notes"], "",
        ]
        if figure["kind"] == "io-diagram":
            lines += ["Editorial summary of documented inputs and outputs; internal architecture is not shown.", ""]
        if m["variants"]:
            lines += ["**Variants:** " + "; ".join(m["variants"]) + ".", ""]
        lines += ["</details>", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_readme(catalog, figures):
    models = sorted_models(catalog["models"])
    counts = Counter(m["category"] for m in models)
    lines = [
        "# Awesome TTS Architectures [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)", "", GENERATED, "",
        "A visual catalog of text-to-speech models, from Tacotron to speech language models. Diagrams, primary sources and short notes for every entry.", "",
        f'**{len(models)} models and families · Reviewed {catalog["as_of"]}**', "",
        "[Models](#models) · [Architectures](#architectures) · [2025+ TTS-arxiv-daily collection](docs/tts-arxiv-daily.md) · [Descriptions](docs/model-descriptions.md) · [Timeline](docs/timeline.md) · [Methodology](docs/methodology.md) · [Contribute](CONTRIBUTING.md)", "",
        "The [TTS-arxiv-daily collection](docs/tts-arxiv-daily.md) covers the source list's TTS systems with first paper submissions from **January 1, 2025** onward. Every included family has an image, a description, paper links and an explicit GitHub availability status. The complete screening record is available as [JSON](data/tts-arxiv-daily.json).", "",
        "## Architectures", "",
        "| VAE · VITS | Flow matching · F5-TTS |", "| --- | --- |",
        f'| [![VITS architecture]({figures["vits"]["path"]})](models/flow-vae.md#vits) | [![F5-TTS architecture]({figures["f5-tts"]["path"]})](models/diffusion.md#f5-tts) |', "",
        "| Collection | Models |", "| --- | ---: |",
    ]
    for key, (title, filename, _) in CATEGORIES.items():
        lines.append(f"| [{title}](models/{filename}) | {counts[key]} |")
    lines += [
        "", "Figures are credited to their sources. Editorial input/output diagrams are labeled. [Credits](assets/architectures/CREDITS.md).", "",
        "## Models", "",
        "Every model has an image below. Select a preview or model name for the full figure, description and primary sources.", "",
        "T: text · S: speech or voice reference · A: other audio · I: image · V: video. [Scope and labels](docs/methodology.md#modalities-and-interaction).", "",
        "| Image | Model | Group | Input → output |", "| --- | --- | --- | --- |",
    ]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Editorial input/output diagram" if figure["kind"] == "io-diagram" else "Source figure"
        alt = escape(cell(f'{m["name"]} — {visual_type}'))
        preview_width = 280
        if figure["kind"] == "source-figure":
            with (ROOT / figure["path"]).open("rb") as asset:
                header = asset.read(24)
            width, height = int.from_bytes(header[16:20], "big"), int.from_bytes(header[20:24], "big")
            preview_width = min(preview_width, round(240 * width / height))
        preview = f'<a href="{link(m)}"><img src="{figure["path"]}" alt="{alt}" width="{preview_width}"></a>'
        if figure["kind"] == "io-diagram":
            preview += "<br><sub>Editorial input/output diagram</sub>"
        lines.append(f'| {preview} | [{cell(m["name"])}]({link(m)}) | {CATEGORIES[m["category"]][2]} | {io(m)} |')
    lines += [
        "", "---", "",
        "[JSON catalog](data/models.json) · [Apache 2.0](LICENSE) · [Third-party figure notice](assets/architectures/FIGURE_NOTICE.md)", "",
    ]
    return "\n".join(lines)


def render_descriptions(catalog, figures):
    models = sorted_models([m for m in catalog["models"] if m.get("description")])
    lines = [
        "# TTS model descriptions · 2025–2026", "", GENERATED, "",
        "[← All models](../README.md#models)", "",
        f'**{len(models)} model families and releases · Reviewed {catalog["as_of"]}**', "",
        "Short explanations of the catalog's 2025–2026 models and family updates, including later releases of older paper families. Each entry includes an image and links to primary sources. Editorial input/output diagrams are labeled. Verified source dates are listed in the [timeline](timeline.md); undated records remain undated.", "",
        "<details>", "<summary>Model index</summary>", "",
    ]
    lines += [f'- [{m["name"]}](#{m["id"]})' for m in models]
    lines += ["", "</details>", "", "## Descriptions", ""]
    for m in models:
        figure = figures[m["id"]]
        visual_type = "Editorial input/output diagram" if figure["kind"] == "io-diagram" else figure["locator"]
        lines += [
            f'<a id="{m["id"]}"></a>', "", f'### {m["name"]}', "",
            m["description"], "",
            f'[Architecture and figure]({link(m, "../")}) · {sources(m)}', "",
            f'![{cell(m["name"])} — {visual_type}](../{figure["path"]})', "",
            f'*{visual_type} · [Source]({figure["source_url"]})*', "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_timeline(catalog):
    known = [m for m in catalog["models"] if m["source_date"]]
    unknown = sorted_models([m for m in catalog["models"] if not m["source_date"]])
    known.sort(key=lambda m: (m["source_date"], m["name"].casefold()), reverse=True)
    lines = ["# Paper and announcement timeline", "", GENERATED, "", "[← Model index](../README.md#models)", "", f'Reviewed as of **{catalog["as_of"]}**. {len(known)} entries have a verified source date; {len(unknown)} are undated in this catalog.', "", "These are dates of the linked paper or explicitly dated announcement. An arXiv submission can precede or follow model/weights/API availability. A paper's first submission date can also precede the release of variants discussed in later revisions. Repository updates, API snapshot suffixes and model training cutoffs are not treated as release dates.", "", "| Source date | Model | Date type | Primary sources |", "| --- | --- | --- | --- |"]
    for m in known:
        lines.append(f'| {m["source_date"]} | [{cell(m["name"])}]({link(m, "../")}) | {m["source_date_kind"]} | {sources(m)} |')
    lines += ["", "## No established source date", "", "These entries remain searchable without assigning a guessed publication or release date.", ""]
    lines += [f'- [{m["name"]}]({link(m, "../")})' for m in unknown]
    return "\n".join(lines).rstrip() + "\n"


def validate_local_links(outputs):
    """Check generated links and authored Markdown links against local files/anchors."""
    pages = {p: p.read_text(encoding="utf-8") for p in ROOT.rglob("*.md") if ".git" not in p.parts and p.name != "model-template.md"}
    pages.update(outputs)
    anchor_cache = {}
    for path, content in pages.items():
        anchors = set(re.findall(r'<a\s+id="([^"]+)"', content))
        for heading in re.findall(r"^#{1,6}\s+(.+)$", content, re.M):
            slug = re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")
            anchors.add(slug)
        anchor_cache[path] = anchors
    for path, content in pages.items():
        # Fenced code examples are not navigable Markdown links.
        content = re.sub(r"```.*?```", "", content, flags=re.S)
        targets = re.findall(r"\[[^\]\n]*\]\(([^)\s]+)\)", content)
        targets += re.findall(r'<(?:img|a)\s+[^>]*?(?:src|href)="([^"]+)"', content)
        # Linked image previews contain an outer link around the image.
        targets += re.findall(r"\[!\[[^\]]*\]\([^)]+\)\]\(([^)]+)\)", content)
        for target in targets:
            if urlsplit(target).scheme or target.startswith("//"):
                continue
            relative, _, anchor = target.partition("#")
            dest = (path.parent / relative).resolve() if relative else path
            if dest not in pages and not dest.exists():
                raise ValueError(f"{path.relative_to(ROOT)}: missing link target {target}")
            if anchor and dest in anchor_cache and anchor not in anchor_cache[dest]:
                raise ValueError(f"{path.relative_to(ROOT)}: missing anchor {target}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate without modifying files; fail on stale generated files")
    args = parser.parse_args()
    try:
        catalog = json.loads(DATA.read_text(encoding="utf-8"))
        validate(catalog)
        models = sorted_models(catalog["models"])
        manifest = json.loads(FIGURES.read_text(encoding="utf-8"))
        validate_figures(catalog, manifest, ROOT)
        figures = manifest["models"]
        daily = json.loads(DAILY.read_text(encoding="utf-8"))
        validate_daily(daily, catalog, figures)
        outputs = {
            ROOT / "README.md": render_readme(catalog, figures),
            ROOT / "docs/model-descriptions.md": render_descriptions(catalog, figures),
            ROOT / "docs/timeline.md": render_timeline(catalog),
            ROOT / "docs/tts-arxiv-daily.md": render_daily(daily, catalog, figures, link, sources),
            ROOT / "assets/architectures/CREDITS.md": render_credits(models, manifest),
        }
        for model in models:
            figure = figures[model["id"]]
            if figure["kind"] == "io-diagram":
                outputs[ROOT / figure["path"]] = render_interface(model)
        for key, (_, filename, _) in CATEGORIES.items():
            outputs[ROOT / "models" / filename] = render_category(key, [m for m in models if m["category"] == key], catalog["as_of"], figures)
        validate_local_links(outputs)
        stale = []
        for path, content in outputs.items():
            if args.check:
                if not path.exists() or path.read_text(encoding="utf-8") != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
        if stale:
            raise ValueError("Stale generated files: " + ", ".join(stale) + "; run python3 scripts/catalog.py")
        unique_sources = {s["url"] for m in models for s in m["sources"]}
        described = sum(bool(m.get("description")) for m in models)
        print(f'{"Checked" if args.check else "Rendered"} {len(models)} entries, {described} descriptions, {len(unique_sources)} unique primary sources, {len(figures)} model visuals; catalog integrity, figure assets and local links OK.')
    except (ValueError, KeyError, TypeError, OSError) as exc:
        print(f"Catalog error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
